spring:
  application:
    name: Wellness App - Numbers Don't Lie
    description: A wellness application to track and improve your health metrics.
  profiles:
    active: local

vaadin:
  launch-browser: true
